### ISSUE TITLE
Segmentation violation running validator with Aiakos + Yubihsm-go

### ISSUE THREAD

**Issue by fumecow** [certusone/yubihsm-go#2]
The system was left running overnight on the latest master branch for cosmos-sdk patched with Aiakos initialization.  We validated approx. 8200 blocks before the segfault.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xcd168d]

goroutine 31 [running]:
github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go/securechannel.(*SecureChannel).SendEncryptedCommand(0x0, 0xc00553df58, 0x0, 0x0, 0x0, 0x0)
        /home/gopath/src/github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go/securechannel/channel.go:184 +0x4d
github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go.(*SessionManager).household.func1(0xc0018a6850)
        /home/gopath/src/github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go/manager.go:75 +0x166
github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go.(*SessionManager).household(0xc0018a6850)
        /home/gopath/src/github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go/manager.go:122 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go.NewSessionManager.func1(0xc0018a6850)
        /home/gopath/src/github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go/manager.go:59 +0x2b
created by github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go.NewSessionManager
        /home/gopath/src/github.com/cosmos/cosmos-sdk/vendor/github.com/certusone/yubihsm-go/manager.go:57 +0x1ce

**Comment by hendrikhofstadt** [comment]
Thanks for the report. We are looking into it.

**Comment by hendrikhofstadt** [comment]
@fumecow We've been able to reproduce it. This is related to session recreation. A fix will be coming soon.

**Comment by hendrikhofstadt** [comment]
A fix was implemented in the latest version. Thanks again for the report

**Comment by fumecow** [comment]
great thanks for the rapid response!
